# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [24]:
import numpy as np

po = print

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [25]:
A = np.arange(1, 16).reshape(3,5)

In [26]:
print(A.ndim)   #  dimensions  
print(A.shape) # array
print(A.size)       # number of items
print(A.dtype)  # print  data type 
print(A.itemsize)   #  bytes of each element

2
(3, 5)
15
int32
4


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [27]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [28]:
print("Minus")
print(B-C)  # plus
print("Plus")
print(B+C)  # minus
print("Matris multiplication")
print(B@C)  # matrix multiplication
print("mulitplication per element, just 4 fun")
print(B*C)  # multiplication per element

Minus
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Plus
[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
Matris multiplication
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]
mulitplication per element, just 4 fun
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [29]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
#TODO: refactor
exponent = np.exp(D)
print(exponent)  #NOTE: exponential, är detta verklgein korrekt? lite osäker vad som förväntas

print('Calculcate the minimum value in each row:')
print(np.min(D, axis = 1))  

print('Calculcate the minimum value in each column:')
print(np.min(D, axis = 0)) 

print('Find the index value for the minimum value in the whole matrix (hint: use np.argmin).')
print(np.argmin(D))

print('Find the index value for the maximum value in each row (hint: use np.argmax).')
print(np.argmax(D, axis=1))

print("Calculate the sum of all elements in D:")
print(np.sum(D))

print('calculate the mean of each column in D:')
print(np.mean(D, axis=0))

print('Caluclate the media of each column in D:')
print(np.median(D, axis=0))



[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
Calculcate the minimum value in each row:
[1 4 7]
Calculcate the minimum value in each column:
[1 2 3]
Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
0
Find the index value for the maximum value in each row (hint: use np.argmax).
[2 2 2]
Calculate the sum of all elements in D:
45
calculate the mean of each column in D:
[4. 5. 6.]
Caluclate the media of each column in D:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [31]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [32]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [33]:
"""If you have fewer indexes then dimensions, the missing is considered to be ":" which Python fills in automatically.
in the case where A[1], Python reads this as A[1,:]"""
print(A[1])  # same as A[1]S
print(A[1,:])  # same as A[1]
print(A[1] == A[1,:])  # all rows, column 2


[ 6  7  8  9 10]
[ 6  7  8  9 10]
[ True  True  True  True  True]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [34]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [35]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [36]:
#Flatten
for i in A.flatten():
    print(i)
#Ravel (borde var unravel? 🙄)
for i in A.ravel():
    print(i)





1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [37]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

#TODO: For debugging/understading, remove
print(len(b)) # number of matrices in 3D array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
2


In [38]:
"""a is set by creating 30 numbers from 0 to 29.
b then reshapes a, into a 3D array.  2 blocks, each block has 3 rows, each row has -1 = which mean autmatic caluclation of number of columns.
A 3D array has 3 dimensions.
The first dimension has 2 blocks (matrixes?),
the second dimension has 3 rows per block,
the third axe has 5 columns per row.
"""

'a is set by creating 30 numbers from 0 to 29.\nb then reshapes a, into a 3D array.  2 blocks, each block has 3 rows, each row has -1 = which mean autmatic caluclation of number of columns.\nA 3D array has 3 dimensions.\nThe first dimension has 2 blocks (matrixes?),\nthe second dimension has 3 rows per block,\nthe third axe has 5 columns per row.\n'

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [39]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [40]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [41]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [42]:
def add_mult_matrices(mat1, mat2, method="add"):
    """Adds and multiplies two matrices."""
    isArray1 = isinstance(mat1, np.ndarray)
    isArray2 = isinstance(mat2, np.ndarray)
    if method not in ['multiply', 'add']:
        raise ValueError("Method must be 'multiply' or 'add'.")
    
    if isArray1 is False or isArray2 is False:
        raise ValueError("Both inputs must be numpy arrayer.")

    if method == "multiply":
        if mat1.shape[-1] != mat2.shape[0]:    
            raise ValueError(f"Cannot multiply shapes {mat1.shape} and {mat2.shape}")
        return mat1 @ mat2
    
    additionMatrixes = mat1 + mat2
    if additionMatrixes.shape != mat1.shape:
        raise ValueError("Matrix addition not possible with given shapes.")
    return additionMatrixes
print("Addition and multiplication of matrices:")
print("Matrix A:")
print(A)
print("Matrix b:")
print(b)
print("Addition (A + b):")
print(add_mult_matrices(A, b, "add"))
print("Muliplication (A @ b):")
print(add_mult_matrices(A, b, "multiply"))

Addition and multiplication of matrices:
Matrix A:
[[1 2]
 [3 4]]
Matrix b:
[2 2]
Addition (A + b):
[[3 4]
 [5 6]]
Muliplication (A @ b):
[ 6 14]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [43]:
"""We are using short cuts in this assignemtn, meaning we use x as common identifier, and _Assignment characters to identify the sub task."""
#x = (4,3) skapar bara en tuple...tror ajg.. vi vill ha den som array
a = assigment = "10.1.1"
b = "10.1.2"
x = np.array([4,3])
#10.1.1
print("ass 10.1.1")
print(f"x={x}")

print()
print(f"{a}.a Dimension: {x.size}") 

x_b = x*5
print(f"{a}.b muliply with 5:{x_b}")
print()

x_c = x*3
print(f"{a}.c multi 3: {x_c}")
print()

x_d=add_mult_matrices(x_b,x_c)
print(f"{a}.d addition b+c: {x_d}")
print()

x_e = 8*x
print(f"{a}.e multiply with 8: {x_e}")
print()

x_f=(4*x)-x #parenthis unecessary, but more as reminder (PEMDAS 4 EVER :D )
print(f"{a}.f result:{x_f}")
print()

x_g = x.T #Hittade hur jag ska lösa, men fattar den inte riktigt.. x är ju Transform, som jag fattar det, gör ju om formen på värdet, dvs ändrar inte värdet
#men värdet är ju bara 1 axel just nu, vilket gör att T i sig inte har nåogt att transfioormare 
# om x var en kolumnvektor, så har det blivit en rad vektor?
print(f"{a}.g transformers unite: {x_g} \n but shape is changed?\n x old shape: {x.shape}\n x_t shape: {x_g.shape}")
#vi testar
y = np.array([[4], [3]])
y_g = y.T
print(f"{a}.g med y: {y_g}")
print("original",y.shape)
print("ny shape?:",y_g.shape)

print()
x_i = np.linalg.norm(x) #TODO: gemini förelsog vid google sök, jag testade.. här måste jag kontrollera  
print(f"{a}.i Norm ||x||: {x_i}")
print()



ass 10.1.1
x=[4 3]

10.1.1.a Dimension: 2
10.1.1.b muliply with 5:[20 15]

10.1.1.c multi 3: [12  9]

10.1.1.d addition b+c: [32 24]

10.1.1.e multiply with 8: [32 24]

10.1.1.f result:[12  9]

10.1.1.g transformers unite: [4 3] 
 but shape is changed?
 x old shape: (2,)
 x_t shape: (2,)
10.1.1.g med y: [[4 3]]
original (2, 1)
ny shape?: (1, 2)

10.1.1.i Norm ||x||: 5.0



In [44]:

print("ass 10.1.2")
#v = np.array([[3],[7],[0],[11]]) #TODO: känns fel.. finns det smartare sätt?
v = np.array([3,7,0,11]).reshape(-1,1) #det fanns det!

print(f"{b}.a Dimension: {v.size} (antal element)")
print(f"{b}.a Dimension: {v.shape} (formen?)") #aah, 4,1 , 4 element i 1 kolumn

print()
v_b = 2*v
print(f"{b}.b 2v: {v_b}")

print()
v_c = (5*v + 2*v)
print(f"{b}.c 5v+2v: {v_c}")

print()
v_d = 4*v-2*v
print(f"{b}.d 4v-2v: {v_d}")

print()
v_e = v.T #denna borde visa något
print(f"{b}.e \noriginal shape: {v.shape} then {v}\nnew shape after transform: {v_e.shape} now {v_e}") #should actually be like the original here




ass 10.1.2
10.1.2.a Dimension: 4 (antal element)
10.1.2.a Dimension: (4, 1) (formen?)

10.1.2.b 2v: [[ 6]
 [14]
 [ 0]
 [22]]

10.1.2.c 5v+2v: [[21]
 [49]
 [ 0]
 [77]]

10.1.2.d 4v-2v: [[ 6]
 [14]
 [ 0]
 [22]]

10.1.2.e 
original shape: (4, 1) then [[ 3]
 [ 7]
 [ 0]
 [11]]
new shape after transform: (1, 4) now [[ 3  7  0 11]]


In [45]:
"""Uppgift 10.1.3"""
#TODO Städa upp

c = "10.1.3"
print(f"{c}")

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

print(f"v1 = {v1}")
print(f"v2 = {v2}")
print()


v12_a = np.linalg.norm(v1) #beräknda normen på v1
print(f"{c}.a ||v1|| : {v12_a}")
print()

# ||v1 - v2|| TODO: verifiera att detta är rätt?
v12_b = v1 - v2  
norm_diff = np.linalg.norm(v12_b)
print(f"{c}.b ||v1 - v2|| = {norm_diff}")
print(f"  (v1 - v2 = {norm_diff})")


10.1.3
v1 = [4 3 1 5]
v2 = [2 3 1 1]

10.1.3.a ||v1|| : 7.14142842854285

10.1.3.b ||v1 - v2|| = 4.47213595499958
  (v1 - v2 = 4.47213595499958)


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [46]:
c = "Assigment 10.2.1"
def createTheMatrix(arr, set):
    return np.array(arr).reshape(set)
def p(char, text):
    print(f"{c}.{char}) {text}")
    print()
    
A =  createTheMatrix([2, 1, -1, 1, -1, 1],(2, 3))
print(f"{c} A:\n{A}\n")

B = createTheMatrix([4,-2,1,2,-4,-2],(2, 3))
print(f"{c} B:\n{B}\n")
C= createTheMatrix([1,2,2,1],(2, 2))
print(f"{c} C:\n{C}\n")
D= createTheMatrix([3,4,4,3],(2, 2))
print(f"{c} D:\n{D}\n")
E= createTheMatrix([1,2],(2,1))
print(f"{c} E:\n{E}\n")
I= createTheMatrix([1,0,0,1],(2,2))
print(f"{c} F:\n{I}\n")

c_a = 2*A
p("a",f"2xA:{c_a}")

c_b = B-2*A
p("b", f"B-2A: {c_b}")

c_c = 3*C-2*E
p("c",f"3C-2E: {c_c}")

c_d=2*D-3*C
p("d",f"2D-3C: {c_d}")

c_e= D.T+2*D
p("e", f"DT-2D: {c_e}")

c_f = (2*C).T - (2*D).T
p("f",f"2CT-2DT: {c_f}")

#c_g = A.T-B A byter ju shape här, detta går inte??
#p("g", f"AT-B: {c_g}")
p("g", f"AT-B; A.T byter shape på A, bilket gör att substraktion inte fungerar applicera då dessa nu skiljer sig")


#c_h = A@C
#print("h", f"AC: {c_h}")
print("h", f"AC: Olika dimensioner går inte")

c_i = C@D
p("i",f"CD: {c_i}")

c_j = C@B
p("j",f"CB: {c_j}")

c_k = C@I
p("k",f"CI: {c_k}")

c_l = A@B.T
p("l",f"ABT: {c_l}")


Assigment 10.2.1 A:
[[ 2  1 -1]
 [ 1 -1  1]]

Assigment 10.2.1 B:
[[ 4 -2  1]
 [ 2 -4 -2]]

Assigment 10.2.1 C:
[[1 2]
 [2 1]]

Assigment 10.2.1 D:
[[3 4]
 [4 3]]

Assigment 10.2.1 E:
[[1]
 [2]]

Assigment 10.2.1 F:
[[1 0]
 [0 1]]

Assigment 10.2.1.a) 2xA:[[ 4  2 -2]
 [ 2 -2  2]]

Assigment 10.2.1.b) B-2A: [[ 0 -4  3]
 [ 0 -2 -4]]

Assigment 10.2.1.c) 3C-2E: [[ 1  4]
 [ 2 -1]]

Assigment 10.2.1.d) 2D-3C: [[3 2]
 [2 3]]

Assigment 10.2.1.e) DT-2D: [[ 9 12]
 [12  9]]

Assigment 10.2.1.f) 2CT-2DT: [[-4 -4]
 [-4 -4]]

Assigment 10.2.1.g) AT-B; A.T byter shape på A, bilket gör att substraktion inte fungerar applicera då dessa nu skiljer sig

h AC: Olika dimensioner går inte
Assigment 10.2.1.i) CD: [[11 10]
 [10 11]]

Assigment 10.2.1.j) CB: [[  8 -10  -3]
 [ 10  -8   0]]

Assigment 10.2.1.k) CI: [[1 2]
 [2 1]]

Assigment 10.2.1.l) ABT: [[5 2]
 [7 4]]



In [47]:
"""Uppgift 10.2.2"""

A = np.array([2,3,4,5,4,1]).reshape(2,3)
print("A",A)
print()

d_a = A@A.T
print(f"10.2.2 AAT: {d_a}")
print()

A [[2 3 4]
 [5 4 1]]

10.2.2 AAT: [[29 26]
 [26 42]]



In [48]:
print("assigment 10.2.3")
A = np.array([1,2,2,4]).reshape(2,2)
B= np.array([2,1,1,3]).reshape(2,2)
C = np.array([4,3,0,2]).reshape(2,2)
print(f"A :\n{A}\n")
print(f"B :\n{B}\n")
print(f"C :\n{C}\n")

AB = A@B
AC = A@C
print()
print(f"10.2.3.1 AB: {AB}") #skriva ut för att försöka förstå
print(f"10.2.3.1 AC: {AC}") #skriva ut för att försöka förstå

print()
print(f"10.2.3.1 AB == AC: {np.array_equal(AB, AC)} ") #Should be true
print()
print(f"10.2.3.2 B == C: {np.array_equal(B, C)} ") #Should be false


assigment 10.2.3
A :
[[1 2]
 [2 4]]

B :
[[2 1]
 [1 3]]

C :
[[4 3]
 [0 2]]


10.2.3.1 AB: [[ 4  7]
 [ 8 14]]
10.2.3.1 AC: [[ 4  7]
 [ 8 14]]

10.2.3.1 AB == AC: True 

10.2.3.2 B == C: False 


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [49]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [50]:
print(v1.base)
print(v2.base)
#v2=123 NOTE: tankefel, base v2 base, betyder "är baserad på" , värdet är 2 3 som ovan. vilket är en array/lista 
#print(v2.base)
#LAST ELEMENT..

v2[-1] = 123
print(f"v2 is now: {v2}")
print(f"v1 is there fore: {v1}")
print()
print ('v2 is a view of v1, so these means that v2 i pointing to a value with same memory positon as v1.\nIf we change v2, we chage the value in memory, which also v1 is pointing to')

None
[0 1 2 3]
v2 is now: [  2 123]
v1 is there fore: [  0   1   2 123]

v2 is a view of v1, so these means that v2 i pointing to a value with same memory positon as v1.
If we change v2, we chage the value in memory, which also v1 is pointing to
